window.I18N_PAGE_TRANSLATIONS = {
  ...(window.I18N_PAGE_TRANSLATIONS || {}),
  en: {
    home: {
      meta: {
        title: "Servicios Logísticos Alsera",
        description: "SELOASA delivers pharmaceutical storage, transport, and distribution solutions with cold-chain control, traceability, and nationwide coverage in Mexico."
      },
      hero: {
        slide_1: { title: "<span class='text-primary'>GMP's</span> and Multi-Temperature Control", description: "We coordinate storage solutions through our network of strategic partners with COFEPRIS-approved facilities, safeguarding your products in ranges of <strong>2 °C to 8 °C</strong> with 24/7 monitoring and full traceability.", primary_cta: "Learn More", secondary_cta: "Request a Quote", image_alt: "Pharmaceutical Storage" },
        slide_2: { title: "<span class='text-primary'>Nationwide Coverage</span> Safe and Reliable", description: "Dedicated fleet with pharma-qualified units, real-time temperature control, and cargo insurance. We reach every corner of the country while meeting TAPA and GDP standards.", primary_cta: "Our Services", secondary_cta: "Contact Us", image_alt: "Multi-Temperature Transport" },
        slide_3: { title: "<span class='text-primary'>Visibility</span> and <span class='text-primary'>Full Protection</span>", description: "From the design of your distribution network to 24/7 GPS monitoring and perimeter surveillance. We secure your shipments, reduce risks, and guarantee end-to-end traceability.", primary_cta: "How Does It Work?", secondary_cta: "Get a Quote", image_alt: "Distribution and Security" }
      },
      about: { image_alt: "SELOASA Storage Network (Strategic Partners)", kicker: "Who We Are", title: "Comprehensive Logistics Solutions for the Pharmaceutical Industry", description: "At SELOASA, we specialize in logistics and transport for sensitive products. With more than <strong>30 years of experience</strong>, we offer:", point_1: "Managed storage with certified strategic partners in ranges of <strong>2 °C to 8 °C</strong> (COFEPRIS).", point_2: "Multi-temperature transport with <strong>24/7 satellite monitoring</strong>.", point_3: "Design of secure distribution networks: <strong>TAPA</strong>, <strong>GDP</strong>, and armed custody.", point_4: "Full traceability and customized real-time reports.", cta: "Learn More" },
      facts: { kicker: "Key Facts", title: "Leaders in Pharmaceutical Logistics", description: "SELOASA has been recognized for its excellence in storage management through strategic partners, as well as transport and distribution services. Our mission is to guarantee cold chain integrity, security, and traceability from origin to final destination.", phone_label: "Call us for any inquiry", stat_1: "Satisfied Clients", stat_2: "Completed Shipments", stat_3: "On-Time Delivery Rate", image_alt: "Validated Transport Vehicles" },
      services: { kicker: "Our Services", title: "Discover What We Offer", description: "We design specialized logistics solutions for every stage of your pharmaceutical operation, with control, security, and real-time traceability.", read_more: "Read More", card_1: { title: "Specialized Storage", description: "Storage solutions orchestrated through a network of strategic partners with multi-temperature refrigerated chambers (2-8 °C), COFEPRIS licenses, and constant monitoring.", image_alt: "Pharmaceutical Storage" }, card_2: { title: "Pharmaceutical Transport", description: "Own fleet from 1 to 5 tons, validated units with temperature control and real-time GPS monitoring.", image_alt: "Pharmaceutical Transport" }, card_3: { title: "Comprehensive Distribution", description: "Deliveries to hospitals, pharmacies, and patients; reverse logistics, labeling, and regulatory support.", image_alt: "Pharmaceutical Distribution" }, card_4: { title: "Transport Security", description: "24/7 CCTV, armed guards, hybrid GPS, door sensors, and geofences.", image_alt: "Logistics Security" } },
      feature: { kicker: "Our Advantages", title: "Why choose SELOASA?", point_1: { title: "Nationwide Coverage", description: "We take your goods anywhere in Mexico with our own fleet, including remote areas." }, point_2: { title: "Comprehensive Security", description: "24/7 CCTV monitoring, GPS in units, and armed custody to protect your cargo at all times." }, certs_title: "Certifications & Standards", certs_description: "We align with our clients' certifications, such as COFEPRIS, and hold official SCT permits.", certs_cta: "Learn more", image_alt: "SELOASA Monitoring Room" },
      presence: { kicker: "Our Presence", title: "Mexico at the center of our logistics operation", description: "Our network of strategic partners and monitoring systems allow us to coordinate pharmaceutical storage, transport, and distribution with nationwide coverage from Mexico.", badge_1: "Nationwide coverage", badge_2: "Cold chain", badge_3: "24/7 monitoring", globe_hint: "Click on Mexico to highlight our main logistics node.", card_label: "Main hub", card_title: "Mexico", card_description: "From this point we orchestrate routes, operational visibility, and specialized response for critical services across the country.", stat_1: "Coverage across 32 states", stat_2: "24/7 traceable operation", stat_3: "Specialized pharma services", cta: "Request coverage", note: "Our presence starts in Mexico and keeps growing to support every shipment with control and security." },
      quote: { kicker: "Request Your Quote", description: "Complete the form and a logistics specialist will contact you. We will help design the best solution for your shipments and storage integration with our strategic partners.", phone_label: "Do you have questions?", form_title: "Free Quote!", form: { name: "Full Name", email: "Email Address", subject: "Subject", message: "Detail your request (origin, destination, product type, volume, etc.)", submit: "Send Request" } },
      testimonials: { kicker: "Testimonials", title: "What our clients say", items: { RALCA: { role: "Quality Department", text: "\"Working with SELOASA gives us great peace of mind. Their commitment and attention to detail shine through in every delivery.\"" }, roche: { role: "Logistics Department", text: "\"More than a supplier, SELOASA is a true strategic partner for safeguarding our cold chain shipments.\"" }, kalte: { role: "Technical Management", text: "\"We are impressed by their operational rigor and complete traceability. With SELOASA we know our products are in great hands.\"" }, gsk: { role: "National Distribution Management", text: "\"The punctuality and real-time visibility they offer have been a key element in optimizing our distribution.\"" }, vitasanitas: { role: "Supply Coordination", text: "\"Our orders always arrive on time and at the perfect temperature. It's a pleasure to collaborate with such an attentive team.\"" }, octapharma: { role: "Logistics Management", text: "\"We love their agility and responsiveness. Their operational flexibility adapts wonderfully to our daily requirements.\"" }, pg: { role: "Supply Chain Mexico", text: "\"They are extremely efficient and professional in their processes. They inspire great confidence on every route.\"" }, novartis: { role: "Distribution Management", text: "\"Their traceability control and strict regulatory compliance give us the security we need for our distribution.\"" }, pharmafrigo: { role: "Cold Operations", text: "\"Their expertise in controlled temperature handling is outstanding. We trust their team completely.\"" }, alternavida: { role: "General Management", text: "\"We greatly value their friendly service and the dedicated care they put into every single shipment.\"" }, sandoz: { role: "Medical Department", text: "\"Thanks to SELOASA, our medical supplies arrive intact at their destination, ensuring top quality every time.\"" }, bbraun: { role: "Supply Chain", text: "\"The cold chain requires utmost precision, and with SELOASA we know our cargo is never at risk.\"" }, arcar: { role: "Operations Management", text: "\"Over the years they have demonstrated great reliability and professionalism. Without a doubt, our trusted partner.\"" }, vitalmex: { role: "Logistics Coordination", text: "\"We greatly appreciate their punctuality and the flawless care they give to each shipment. They treat our cargo as their own.\"" } } }
    }
  },
  es: {
    home: {
      meta: {
        title: "Servicios Logísticos Alsera",
        description: "SELOASA ofrece almacenaje, transporte y distribucion farmaceutica con cadena de frio, trazabilidad y cobertura nacional en Mexico."
      },
      hero: {
        slide_1: { title: "<span class='text-primary'>GMP's</span> y Control Multitemperatura", description: "Coordinamos soluciones de almacenaje a través de nuestra red de aliados estratégicos con bodegas aprobadas por COFEPRIS, para resguardar tus productos en rangos de <strong>2 °C a 8 °C</strong> con monitoreo 24/7 y trazabilidad total.", primary_cta: "Conoce Más", secondary_cta: "Solicita Cotización", image_alt: "Almacenaje Farmacéutico" },
        slide_2: { title: "<span class='text-primary'>Cobertura Nacional</span> Segura y Confiable", description: "Flota dedicada con unidades calificadas para farma, control de temperatura en tiempo real y seguro de embarque. Llegamos a cualquier rincón del país cumpliendo con estándares TAPA y GDP's.", primary_cta: "Nuestros Servicios", secondary_cta: "Contáctanos", image_alt: "Transporte Multitemperatura" },
        slide_3: { title: "<span class='text-primary'>Visibilidad</span> y <span class='text-primary'>Protección</span> Total", description: "Desde el diseño de tu red de distribución hasta el monitoreo GPS 24/7 y vigilancia perimetral. Aseguramos tus embarques, reducimos riesgos y garantizamos la trazabilidad de principio a fin.", primary_cta: "¿Cómo Funciona?", secondary_cta: "Cotiza Ahora", image_alt: "Distribución y Seguridad" }
      },
      about: {
        image_alt: "Red de Almacenaje SELOASA (Aliados Estratégicos)", kicker: "Quiénes Somos", title: "Soluciones Logísticas Integrales para la Industria Farmacéutica", description: "En SELOASA somos especialistas en logística y transporte de productos sensibles. Con más de <strong>30 años de experiencia</strong>, ofrecemos:", point_1: "Almacenaje gestionado con aliados estratégicos certificados en rangos de <strong>2 °C a 8 °C</strong> (COFEPRIS).", point_2: "Transporte multitemperatura con <strong>monitoreo satelital 24/7</strong>.", point_3: "Diseño de redes de distribución seguras: <strong>TAPA</strong>, <strong>GDP</strong> y custodia armada.", point_4: "Trazabilidad total e informes personalizados en tiempo real.", cta: "Conoce Más"
      },
      facts: { kicker: "Datos Clave", title: "Líderes en Logística Farmacéutica", description: "SELOASA ha sido reconocido por su excelencia en la gestión de almacenaje mediante aliados estratégicos, así como en transporte y distribución. Nuestra misión es garantizar la cadena de frío, la seguridad y la trazabilidad desde origen hasta el destino final.", phone_label: "Llámanos para cualquier consulta", stat_1: "Clientes Satisfechos", stat_2: "Envíos Completados", stat_3: "Tasa de porcentaje de Entrega a Tiempo", image_alt: "Vehículos Validados para Transporte" },
      services: { kicker: "Nuestros Servicios", title: "Descubre lo que Ofrecemos", description: "Diseñamos soluciones logísticas especializadas para cada etapa de tu operación farmacéutica, con control, seguridad y trazabilidad en tiempo real.", read_more: "Leer Más", card_1: { title: "Almacenaje Especializado", description: "Soluciones articuladas mediante una red de aliados estratégicos con cámaras refrigeradas multitemperatura (2-8 °C), licencias COFEPRIS y monitoreo constante.", image_alt: "Almacenaje Farmacéutico" }, card_2: { title: "Transporte Farmacéutico", description: "Flota propia 1-5 ton, unidades validadas con control de temperatura y monitoreo GPS en tiempo real.", image_alt: "Transporte Multitemperatura" }, card_3: { title: "Distribución Integral", description: "Entregas en hospitales, farmacias y pacientes; logística inversa y etiquetado; soporte regulatorio.", image_alt: "Distribución Farmacéutica" }, card_4: { title: "Seguridad en Transporte", description: "CCTV 24/7, guardias armados, GPS híbrido, sensores de apertura y geocercas.", image_alt: "Seguridad Logística" } },
      feature: { kicker: "Nuestros Diferenciales", title: "¿Por qué elegir SELOASA?", point_1: { title: "Cobertura Nacional", description: "Llevamos tu mercancía a cualquier punto de México con flota propia, incluyendo zonas remotas." }, point_2: { title: "Seguridad Integral", description: "Monitoreo CCTV 24/7, GPS en unidades y custodia armada para proteger tu carga en todo momento." }, certs_title: "Certificaciones & Estándares", certs_description: "Nos alineamos a las certificaciones de nuestros clientes, como COFEPRIS, y contamos con permisos oficiales de la SCT.", certs_cta: "Saber más", image_alt: "Sala de Monitoreo SELOASA" },
      presence: { kicker: "Nuestra Presencia", title: "México en el centro de nuestra operación logística", description: "Nuestra red de aliados estratégicos y sistemas de monitoreo nos permiten coordinar almacenaje, transporte y distribución farmacéutica con cobertura nacional desde México.", badge_1: "Cobertura nacional", badge_2: "Cadena de frío", badge_3: "Monitoreo 24/7", globe_hint: "Haz clic sobre México para destacar nuestro nodo principal.", card_label: "Nodo principal", card_title: "México", card_description: "Desde este punto articulamos rutas, visibilidad operativa y respuesta especializada para servicios críticos en toda la República.", stat_1: "Cobertura en 32 estados", stat_2: "Operación trazable 24/7", stat_3: "Servicios farma especializados", cta: "Solicitar cobertura", note: "Nuestra presencia inicia en México y sigue creciendo para acompañar cada embarque con control y seguridad." },
      quote: { kicker: "Solicita Tu Cotización", description: "Completa el formulario y un asesor especializado en logística farma se pondrá en contacto contigo. Te ayudaremos a diseñar la mejor solución para tus envíos y la integración de almacenaje con nuestros aliados estratégicos.", phone_label: "¿Tienes dudas?", form_title: "¡Cotización Sin Costo!", form: { name: "Nombre Completo", email: "Correo Electrónico", subject: "Asunto", message: "Detalle tu solicitud (origen, destino, tipo de producto, volumen, etc.)", submit: "Enviar Solicitud" } },
      testimonials: { kicker: "Testimonios", title: "Lo que dicen nuestros clientes", items: { RALCA: { role: "Departamento de Calidad", text: "\"Trabajar con SELOASA nos da mucha tranquilidad. Se nota su compromiso y la atención al detalle en cada entrega.\"" }, roche: { role: "Departamento de Logística", text: "\"Más que un proveedor, SELOASA es un verdadero aliado estratégico para resguardar nuestros envíos bajo cadena de frío.\"" }, kalte: { role: "Dirección Técnica", text: "\"Nos impresiona su rigor operativo y la trazabilidad en todo momento. Con SELOASA sabemos que el producto está en buenas manos.\"" }, gsk: { role: "Gerencia Nacional de Distribución", text: "\"La puntualidad y la visibilidad en tiempo real que ofrecen ha sido una pieza clave para optimizar nuestra distribución.\"" }, vitasanitas: { role: "Coordinación de Abasto", text: "\"Nuestros pedidos siempre llegan a tiempo y con la temperatura perfecta. Da gusto colaborar con un equipo tan atento.\"" }, octapharma: { role: "Jefatura de Logística", text: "\"Nos encanta su agilidad y capacidad de respuesta. Su flexibilidad operativa se adapta genial a lo que requerimos día a día.\"" }, pg: { role: "Supply Chain México", text: "\"Son sumamente eficientes y profesionales en sus procesos. Transmiten muchísima confianza en cada ruta.\"" }, novartis: { role: "Gestión de Distribución", text: "\"El control de trazabilidad y su estricto apego a las normativas nos dan la seguridad que necesitamos para nuestra distribución.\"" }, pharmafrigo: { role: "Operaciones Frigoríficas", text: "\"Su experiencia en el manejo de temperatura controlada es sobresaliente. Confiamos a ojos cerrados en su equipo.\"" }, alternavida: { role: "Gerencia General", text: "\"Valoramos enormemente el trato cercano y la dedicación especial que le ponen a cada uno de nuestros envíos.\"" }, sandoz: { role: "Departamento Médico", text: "\"Gracias a SELOASA, nuestros insumos médicos llegan intactos a su destino, cuidando siempre la calidad final.\"" }, bbraun: { role: "Supply Chain", text: "\"La cadena de frío requiere máxima precisión, y con SELOASA sabemos que nuestra mercancía nunca corre riesgos.\"" }, arcar: { role: "Gerencia de Operaciones", text: "\"A lo largo de los años nos han demostrado una gran solidez y profesionalismo. Sin duda, son nuestros aliados de confianza.\"" }, vitalmex: { role: "Coordinación de Logística", text: "\"Apreciamos mucho la puntualidad y el cuidado impecable que le dan a cada embarque. Cuidan la carga como si fuera propia.\"" } } }
    }
  },
  al: {
    home: {
      meta: {
        title: "Servicios Logísticos Alsera",
        description: "SELOASA bietet pharmazeutische Lager-, Transport- und Vertriebslosungen mit Kuhlkette, Ruckverfolgbarkeit und landesweiter Abdeckung in Mexiko."
      },
      hero: {
        slide_1: { title: "<span class='text-primary'>GMP's</span> und Mehrtemperaturkontrolle", description: "Wir verfügen über dedizierte und gemeinsame Lager, die von COFEPRIS zugelassen sind, um Ihre Produkte in Bereichen von <strong>2 °C bis 8 °C</strong> mit 24/7-Überwachung und vollständiger Rückverfolgbarkeit zu lagern.", primary_cta: "Mehr erfahren", secondary_cta: "Angebot anfordern", image_alt: "Pharmazeutische Lagerung" },
        slide_2: { title: "<span class='text-primary'>Nationale Abdeckung</span> Sicher und zuverlässig", description: "Dedizierte Flotte mit für Pharma qualifizierten Einheiten, Temperaturkontrolle in Echtzeit und Transportversicherung. Wir erreichen jeden Winkel des Landes unter Einhaltung der TAPA- und GDP-Standards.", primary_cta: "Unsere Dienstleistungen", secondary_cta: "Kontaktieren Sie uns", image_alt: "Mehrtemperaturtransport" },
        slide_3: { title: "<span class='text-primary'>Sichtbarkeit</span> und <span class='text-primary'>vollständiger Schutz</span>", description: "Vom Design Ihres Vertriebsnetzes bis hin zur 24/7-GPS-Überwachung und Perimetersicherung. Wir schützen Ihre Sendungen, reduzieren Risiken und garantieren eine Rückverfolgbarkeit von Anfang bis Ende.", primary_cta: "Wie funktioniert es?", secondary_cta: "Jetzt anfragen", image_alt: "Distribution und Sicherheit" }
      },
      about: { image_alt: "SELOASA-Einrichtungen (Lager)", kicker: "Wer wir sind", title: "Umfassende Logistiklösungen für die Pharmaindustrie", description: "Bei SELOASA sind wir auf Logistik und Transport sensibler Produkte spezialisiert. Mit mehr als <strong>30 Jahren Erfahrung</strong> bieten wir:", point_1: "Zertifizierte Lagerung in Bereichen von <strong>2 °C bis 8 °C</strong> (COFEPRIS).", point_2: "Mehrtemperaturtransport mit <strong>24/7-Satellitenüberwachung</strong>.", point_3: "Entwurf sicherer Vertriebsnetze: <strong>TAPA</strong>, <strong>GDP</strong> und bewaffnete Begleitung.", point_4: "Vollständige Rückverfolgbarkeit und personalisierte Berichte in Echtzeit.", cta: "Mehr erfahren" },
      facts: { kicker: "Kennzahlen", title: "Führend in pharmazeutischer Logistik", description: "SELOASA wurde für seine Exzellenz in Lager-, Transport- und Vertriebsdienstleistungen anerkannt. Unsere Mission ist es, die Kühlkette, Sicherheit und Rückverfolgbarkeit vom Ursprung bis zum Endziel zu gewährleisten.", phone_label: "Rufen Sie uns bei Fragen an", stat_1: "Zufriedene Kunden", stat_2: "Abgeschlossene Sendungen", stat_3: "Pünktliche Lieferquote", image_alt: "Validierte Transportfahrzeuge" },
      services: { kicker: "Unsere Dienstleistungen", title: "Entdecken Sie unser Angebot", description: "Wir entwickeln spezialisierte Logistiklösungen für jede Phase Ihres pharmazeutischen Betriebs, mit Kontrolle, Sicherheit und Rückverfolgbarkeit in Echtzeit.", read_more: "Mehr lesen", card_1: { title: "Spezialisierte Lagerung", description: "GMP-Lösungen mit Mehrtemperatur-Kühlkammern (2-8 °C), COFEPRIS-Lizenz und permanenter Temperaturüberwachung.", image_alt: "Pharmazeutische Lagerung" }, card_2: { title: "Pharmazeutischer Transport", description: "Eigene Flotte von 1 bis 5 Tonnen, validierte Einheiten mit Temperaturkontrolle und GPS-Überwachung in Echtzeit.", image_alt: "Pharmazeutischer Transport" }, card_3: { title: "Umfassende Distribution", description: "Lieferungen an Krankenhäuser, Apotheken und Patienten; Rücknahmelogistik, Etikettierung und regulatorische Unterstützung.", image_alt: "Pharmazeutische Distribution" }, card_4: { title: "Transportsicherheit", description: "24/7-CCTV, bewaffnete Wachen, Hybrid-GPS, Türsensoren und Geofencing.", image_alt: "Logistiksicherheit" } },
      feature: { kicker: "Unsere Vorteile", title: "Warum SELOASA wählen?", point_1: { title: "Nationale Abdeckung", description: "Wir bringen Ihre Waren mit eigener Flotte an jeden Punkt Mexikos, auch in abgelegene Gebiete." }, point_2: { title: "Umfassende Sicherheit", description: "24/7-CCTV-Überwachung, GPS in den Einheiten und bewaffnete Begleitung zum Schutz Ihrer Fracht." }, certs_title: "Zertifizierungen & Standards", certs_description: "Wir richten uns nach den Zertifizierungen unserer Kunden wie COFEPRIS und verfügen über offizielle SCT-Genehmigungen.", certs_cta: "Mehr erfahren", image_alt: "SELOASA-Überwachungsraum" },
      presence: { kicker: "Unsere Präsenz", title: "Mexiko im Zentrum unserer Logistik", description: "Unsere Infrastruktur und Überwachung ermöglichen es uns, pharmazeutische Lagerung, Transport und Distribution mit landesweiter Abdeckung von Mexiko aus zu koordinieren.", badge_1: "Landesweite Abdeckung", badge_2: "Kühlkette", badge_3: "24/7-Überwachung", globe_hint: "Klicken Sie auf Mexiko, um unseren wichtigsten Logistikstandort hervorzuheben.", card_label: "Hauptstandort", card_title: "Mexiko", card_description: "Von hier aus koordinieren wir Routen, operative Transparenz und spezialisierte Reaktionen für kritische Dienste im ganzen Land.", stat_1: "Abdeckung in 32 Bundesstaaten", stat_2: "24/7 rückverfolgbare Abläufe", stat_3: "Spezialisierte Pharma-Services", cta: "Abdeckung anfragen", note: "Unsere Präsenz beginnt in Mexiko und wächst weiter, um jede Sendung mit Kontrolle und Sicherheit zu begleiten." },
      quote: { kicker: "Fordern Sie Ihr Angebot an", description: "Füllen Sie das Formular aus und ein spezialisierter Logistikberater wird Sie kontaktieren. Wir helfen Ihnen, die beste Lösung für Ihre Sendungen und Lagerung zu entwerfen.", phone_label: "Haben Sie Fragen?", form_title: "Kostenloses Angebot!", form: { name: "Vollständiger Name", email: "E-Mail-Adresse", subject: "Betreff", message: "Beschreiben Sie Ihre Anfrage (Ursprung, Ziel, Produkttyp, Volumen usw.)", submit: "Anfrage senden" } },
      testimonials: { kicker: "Referenzen", title: "Was unsere Kunden sagen", items: { RALCA: { role: "Qualitätsabteilung", text: "\"Ein engagiertes Unternehmen, das sich seinen und unseren Prozessen verpflichtet fühlt.\"" }, roche: { role: "Logistikabteilung", text: "\"Ein strategischer Partner für die Einhaltung unserer Kühlkettensendungen.\"" }, kalte: { role: "Technische Leitung", text: "\"Streng, zuverlässig und mit vollständiger Rückverfolgbarkeit. SELOASA ist eine Garantie für Compliance.\"" }, gsk: { role: "Nationale Vertriebsleitung", text: "\"Die Zuverlässigkeit und Sichtbarkeit von SELOASA waren für unseren Betrieb entscheidend.\"" }, vitasanitas: { role: "Versorgungskoordination", text: "\"Wir erhalten unsere Bestellungen pünktlich und ohne Temperaturschwankungen.\"" }, octapharma: { role: "Leitung Logistik", text: "\"Die operative Flexibilität von SELOASA hat sich perfekt an unsere Bedürfnisse angepasst.\"" }, pg: { role: "Supply Chain Mexiko", text: "\"Effizient, schnell und mit klar definierten Prozessen. Ein Unternehmen, das Vertrauen schafft.\"" }, novartis: { role: "Vertriebsmanagement", text: "\"Die Rückverfolgbarkeit und Regelkonformität von SELOASA waren entscheidend für unsere logistische Kontrolle.\"" }, pharmafrigo: { role: "Kühlkettenbetrieb", text: "\"Ihre Erfahrung im Kühlbereich ist unübertroffen. Wir vertrauen ihrem Management voll und ganz.\"" }, alternavida: { role: "Geschäftsleitung", text: "\"Alternavida zeichnet sich durch sein Engagement bei jeder Sendung aus.\"" }, sandoz: { role: "Medizinische Abteilung", text: "\"Dank SELOASA kommt unser Produkt in perfektem Zustand an.\"" }, bbraun: { role: "Supply Chain", text: "\"Mit SELOASA versagt unsere Kühlkette nie.\"" }, arcar: { role: "Betriebsleitung", text: "\"ARCAR vertraut voll und ganz auf die Erfahrung von SELOASA.\"" }, vitalmex: { role: "Logistikkoordination", text: "\"VITALMEX schätzt die Pünktlichkeit und die extreme Sorgfalt bei jeder Sendung.\"" } } }
    }
  },
  pt: {
    home: {
      meta: {
        title: "Servicios Logísticos Alsera",
        description: "A SELOASA oferece armazenagem, transporte e distribuicao farmaceutica com cadeia fria, rastreabilidade e cobertura nacional no Mexico."
      },
      hero: {
        slide_1: { title: "<span class='text-primary'>GMP's</span> e Controle Multitemperatura", description: "Contamos com armazéns dedicados e compartilhados, aprovados pela COFEPRIS, para armazenar seus produtos em faixas de <strong>2 °C a 8 °C</strong> com monitoramento 24/7 e rastreabilidade total.", primary_cta: "Saiba Mais", secondary_cta: "Solicite uma Cotação", image_alt: "Armazenagem Farmacêutica" },
        slide_2: { title: "<span class='text-primary'>Cobertura Nacional</span> Segura e Confiável", description: "Frota dedicada com unidades qualificadas para o setor farmacêutico, controle de temperatura em tempo real e seguro de embarque. Chegamos a qualquer ponto do país cumprindo padrões TAPA e GDP's.", primary_cta: "Nossos Serviços", secondary_cta: "Fale Conosco", image_alt: "Transporte Multitemperatura" },
        slide_3: { title: "<span class='text-primary'>Visibilidade</span> e <span class='text-primary'>Proteção</span> Total", description: "Desde o desenho da sua rede de distribuição até o monitoramento GPS 24/7 e vigilância perimetral. Protegemos seus embarques, reduzimos riscos e garantimos rastreabilidade de ponta a ponta.", primary_cta: "Como Funciona?", secondary_cta: "Solicite Agora", image_alt: "Distribuição e Segurança" }
      },
      about: { image_alt: "Instalações da SELOASA (Armazém)", kicker: "Quem Somos", title: "Soluções Logísticas Integrais para a Indústria Farmacêutica", description: "Na SELOASA somos especialistas em logística e transporte de produtos sensíveis. Com mais de <strong>30 anos de experiência</strong>, oferecemos:", point_1: "Armazenagem certificada em faixas de <strong>2 °C a 8 °C</strong> (COFEPRIS).", point_2: "Transporte multitemperatura com <strong>monitoramento satelital 24/7</strong>.", point_3: "Desenho de redes de distribuição seguras: <strong>TAPA</strong>, <strong>GDP</strong> e escolta armada.", point_4: "Rastreabilidade total e relatórios personalizados em tempo real.", cta: "Saiba Mais" },
      facts: { kicker: "Dados-Chave", title: "Líderes em Logística Farmacêutica", description: "A SELOASA foi reconhecida por sua excelência em serviços de armazenagem, transporte e distribuição. Nossa missão é garantir a cadeia fria, a segurança e a rastreabilidade desde a origem até o destino final.", phone_label: "Ligue para qualquer consulta", stat_1: "Clientes Satisfeitos", stat_2: "Envios Concluídos", stat_3: "Taxa de Entrega no Prazo", image_alt: "Veículos validados para transporte" },
      services: { kicker: "Nossos Serviços", title: "Descubra o que Oferecemos", description: "Desenhamos soluções logísticas especializadas para cada etapa da sua operação farmacêutica, com controle, segurança e rastreabilidade em tempo real.", read_more: "Ler Mais", card_1: { title: "Armazenagem Especializada", description: "Soluções GMP com câmaras refrigeradas multitemperatura (2-8 °C), licença COFEPRIS e monitoramento constante de temperatura.", image_alt: "Armazenagem Farmacêutica" }, card_2: { title: "Transporte Farmacêutico", description: "Frota própria de 1 a 5 toneladas, unidades validadas com controle de temperatura e monitoramento GPS em tempo real.", image_alt: "Transporte Farmacêutico" }, card_3: { title: "Distribuição Integral", description: "Entregas em hospitais, farmácias e pacientes; logística reversa, etiquetagem e suporte regulatório.", image_alt: "Distribuição Farmacêutica" }, card_4: { title: "Segurança no Transporte", description: "CCTV 24/7, guardas armados, GPS híbrido, sensores de abertura e geocercas.", image_alt: "Segurança Logística" } },
      feature: { kicker: "Nossos Diferenciais", title: "Por que escolher a SELOASA?", point_1: { title: "Cobertura Nacional", description: "Levamos sua mercadoria a qualquer ponto do México com frota própria, inclusive zonas remotas." }, point_2: { title: "Segurança Integral", description: "Monitoramento CCTV 24/7, GPS nas unidades e escolta armada para proteger sua carga em todo momento." }, certs_title: "Certificações & Padrões", certs_description: "Alinhamos nossas operações às certificações de nossos clientes, como COFEPRIS, e contamos com permissões oficiais da SCT.", certs_cta: "Saber mais", image_alt: "Sala de monitoramento SELOASA" },
      presence: { kicker: "Nossa Presença", title: "México no centro da nossa operação logística", description: "Nossa infraestrutura e monitoramento nos permitem coordenar armazenagem, transporte e distribuição farmacêutica com cobertura nacional a partir do México.", badge_1: "Cobertura nacional", badge_2: "Cadeia fria", badge_3: "Monitoramento 24/7", globe_hint: "Clique no México para destacar nosso principal ponto logístico.", card_label: "Hub principal", card_title: "México", card_description: "A partir deste ponto articulamos rotas, visibilidade operacional e resposta especializada para serviços críticos em todo o país.", stat_1: "Cobertura em 32 estados", stat_2: "Operação rastreável 24/7", stat_3: "Serviços farmacêuticos especializados", cta: "Solicitar cobertura", note: "Nossa presença começa no México e continua crescendo para apoiar cada envio com controle e segurança." },
      quote: { kicker: "Solicite sua Cotação", description: "Preencha o formulário e um consultor especializado em logística farmacêutica entrará em contato com você. Vamos ajudar a desenhar a melhor solução para seus envios e armazenagem.", phone_label: "Tem dúvidas?", form_title: "Cotação Sem Custo!", form: { name: "Nome Completo", email: "Correio Eletrônico", subject: "Assunto", message: "Detalhe sua solicitação (origem, destino, tipo de produto, volume etc.)", submit: "Enviar Solicitação" } },
      testimonials: { kicker: "Depoimentos", title: "O que dizem nossos clientes", items: { RALCA: { role: "Departamento de Qualidade", text: "\"Uma empresa dedicada e comprometida com seus e nossos processos.\"" }, roche: { role: "Departamento de Logística", text: "\"Um parceiro estratégico para o cumprimento de nossos envios sob cadeia fria.\"" }, kalte: { role: "Direção Técnica", text: "\"Rigorosos, confiáveis e com rastreabilidade total. A SELOASA é garantia de cumprimento.\"" }, gsk: { role: "Gerência Nacional de Distribuição", text: "\"A confiabilidade e a visibilidade oferecidas pela SELOASA foram essenciais para nossa operação.\"" }, vitasanitas: { role: "Coordenação de Abastecimento", text: "\"Recebemos nossos pedidos com pontualidade e sem variações de temperatura.\"" }, octapharma: { role: "Chefia de Logística", text: "\"A flexibilidade operacional da SELOASA se adaptou perfeitamente às nossas necessidades.\"" }, pg: { role: "Supply Chain México", text: "\"Eficientes, rápidos e com processos bem definidos. Uma empresa que inspira confiança.\"" }, novartis: { role: "Gestão de Distribuição", text: "\"A rastreabilidade e o cumprimento normativo da SELOASA foram fundamentais para nosso controle logístico.\"" }, pharmafrigo: { role: "Operações de Frio", text: "\"Sua experiência em frio é incomparável. Confiamos plenamente em sua gestão.\"" }, alternavida: { role: "Gerência Geral", text: "\"A Alternavida se destaca pelo compromisso em cada envio.\"" }, sandoz: { role: "Departamento Médico", text: "\"Graças à SELOASA, nosso produto chega em perfeitas condições.\"" }, bbraun: { role: "Supply Chain", text: "\"Com a SELOASA, nossa cadeia fria nunca falha.\"" }, arcar: { role: "Gerência de Operações", text: "\"A ARCAR confia plenamente na trajetória da SELOASA.\"" }, vitalmex: { role: "Coordenação de Logística", text: "\"A VITALMEX valoriza a pontualidade e o cuidado extremo em cada envio.\"" } } }
    }
  },
  fr: {
    home: {
      meta: {
        title: "Servicios Logísticos Alsera",
        description: "SELOASA propose des solutions de stockage, transport et distribution pharmaceutiques avec chaine du froid, tracabilite et couverture nationale au Mexique."
      },
      hero: {
        slide_1: { title: "<span class='text-primary'>GMP's</span> et contrôle multi-température", description: "Nous disposons d'entrepôts dédiés et partagés approuvés par la COFEPRIS pour stocker vos produits dans des plages de <strong>2 °C à 8 °C</strong> avec une surveillance 24/7 et une traçabilité totale.", primary_cta: "En savoir plus", secondary_cta: "Demander un devis", image_alt: "Stockage pharmaceutique" },
        slide_2: { title: "<span class='text-primary'>Couverture nationale</span> sûre et fiable", description: "Flotte dédiée avec des unités qualifiées pour le secteur pharmaceutique, contrôle de température en temps réel et assurance de chargement. Nous atteignons chaque coin du pays tout en respectant les normes TAPA et GDP.", primary_cta: "Nos services", secondary_cta: "Contactez-nous", image_alt: "Transport multi-température" },
        slide_3: { title: "<span class='text-primary'>Visibilité</span> et <span class='text-primary'>protection</span> totale", description: "De la conception de votre réseau de distribution à la surveillance GPS 24/7 et à la sécurité périmétrique. Nous sécurisons vos expéditions, réduisons les risques et garantissons une traçabilité de bout en bout.", primary_cta: "Comment ça fonctionne ?", secondary_cta: "Demandez maintenant", image_alt: "Distribution et sécurité" }
      },
      about: { image_alt: "Installations SELOASA (Entrepôt)", kicker: "Qui sommes-nous", title: "Solutions logistiques intégrales pour l'industrie pharmaceutique", description: "Chez SELOASA, nous sommes spécialisés dans la logistique et le transport de produits sensibles. Avec plus de <strong>30 ans d'expérience</strong>, nous proposons :", point_1: "Stockage certifié dans des plages de <strong>2 °C à 8 °C</strong> (COFEPRIS).", point_2: "Transport multi-température avec <strong>surveillance satellitaire 24/7</strong>.", point_3: "Conception de réseaux de distribution sécurisés : <strong>TAPA</strong>, <strong>GDP</strong> et escorte armée.", point_4: "Traçabilité totale et rapports personnalisés en temps réel.", cta: "En savoir plus" },
      facts: { kicker: "Données clés", title: "Leaders en logistique pharmaceutique", description: "SELOASA a été reconnue pour son excellence dans les services de stockage, de transport et de distribution. Notre mission est de garantir la chaîne du froid, la sécurité et la traçabilité depuis l'origine jusqu'à la destination finale.", phone_label: "Appelez-nous pour toute demande", stat_1: "Clients satisfaits", stat_2: "Expéditions réalisées", stat_3: "Taux de livraison à temps", image_alt: "Véhicules validés pour le transport" },
      services: { kicker: "Nos services", title: "Découvrez ce que nous proposons", description: "Nous concevons des solutions logistiques spécialisées pour chaque étape de votre opération pharmaceutique, avec contrôle, sécurité et traçabilité en temps réel.", read_more: "En savoir plus", card_1: { title: "Stockage spécialisé", description: "Solutions GMP avec chambres froides multi-températures (2-8 °C), licence COFEPRIS et surveillance constante de la température.", image_alt: "Stockage pharmaceutique" }, card_2: { title: "Transport pharmaceutique", description: "Flotte propre de 1 à 5 tonnes, unités validées avec contrôle de température et surveillance GPS en temps réel.", image_alt: "Transport pharmaceutique" }, card_3: { title: "Distribution intégrale", description: "Livraisons aux hôpitaux, pharmacies et patients ; logistique inverse, étiquetage et support réglementaire.", image_alt: "Distribution pharmaceutique" }, card_4: { title: "Sécurité du transport", description: "CCTV 24/7, gardes armés, GPS hybride, capteurs d'ouverture et géorepérage.", image_alt: "Sécurité logistique" } },
      feature: { kicker: "Nos atouts", title: "Pourquoi choisir SELOASA ?", point_1: { title: "Couverture nationale", description: "Nous acheminons votre marchandise vers tout point du Mexique avec notre propre flotte, y compris les zones éloignées." }, point_2: { title: "Sécurité intégrale", description: "Surveillance CCTV 24/7, GPS dans les unités et escorte armée pour protéger votre cargaison à tout moment." }, certs_title: "Certifications & standards", certs_description: "Nous nous alignons sur les certifications de nos clients, comme COFEPRIS, et disposons de permis officiels de la SCT.", certs_cta: "En savoir plus", image_alt: "Salle de surveillance SELOASA" },
      presence: { kicker: "Notre présence", title: "Le Mexique au centre de notre opération logistique", description: "Notre infrastructure et notre surveillance nous permettent de coordonner le stockage, le transport et la distribution pharmaceutiques avec une couverture nationale depuis le Mexique.", badge_1: "Couverture nationale", badge_2: "Chaîne du froid", badge_3: "Surveillance 24/7", globe_hint: "Cliquez sur le Mexique pour mettre en avant notre principal nœud logistique.", card_label: "Nœud principal", card_title: "Mexique", card_description: "Depuis ce point, nous orchestrons les itinéraires, la visibilité opérationnelle et la réponse spécialisée pour les services critiques à travers le pays.", stat_1: "Couverture dans 32 États", stat_2: "Opération traçable 24/7", stat_3: "Services pharma spécialisés", cta: "Demander une couverture", note: "Notre présence commence au Mexique et continue de croître pour accompagner chaque expédition avec contrôle et sécurité." },
      quote: { kicker: "Demandez votre devis", description: "Complétez le formulaire et un conseiller spécialisé en logistique pharmaceutique vous contactera. Nous vous aiderons à concevoir la meilleure solution pour vos expéditions et votre stockage.", phone_label: "Vous avez des questions ?", form_title: "Devis gratuit !", form: { name: "Nom complet", email: "Adresse e-mail", subject: "Sujet", message: "Détaillez votre demande (origine, destination, type de produit, volume, etc.)", submit: "Envoyer la demande" } },
      testimonials: { kicker: "Témoignages", title: "Ce que disent nos clients", items: { RALCA: { role: "Département qualité", text: "\"Une entreprise dévouée et engagée envers ses processus et les nôtres.\"" }, roche: { role: "Département logistique", text: "\"Un partenaire stratégique pour le respect de nos expéditions sous chaîne du froid.\"" }, kalte: { role: "Direction technique", text: "\"Rigoureux, fiables et avec une traçabilité totale. SELOASA est une garantie de conformité.\"" }, gsk: { role: "Direction nationale de la distribution", text: "\"La fiabilité et la visibilité offertes par SELOASA ont été essentielles pour notre opération.\"" }, vitasanitas: { role: "Coordination des approvisionnements", text: "\"Nous recevons nos commandes avec ponctualité et sans variation de température.\"" }, octapharma: { role: "Responsable logistique", text: "\"La flexibilité opérationnelle de SELOASA s'est parfaitement adaptée à nos besoins.\"" }, pg: { role: "Supply Chain Mexique", text: "\"Efficaces, rapides et avec des processus bien définis. Une entreprise qui inspire confiance.\"" }, novartis: { role: "Gestion de la distribution", text: "\"La traçabilité et le respect des normes de SELOASA ont été essentiels pour notre contrôle logistique.\"" }, pharmafrigo: { role: "Opérations frigorifiques", text: "\"Leur expertise du froid est inégalée. Nous faisons pleinement confiance à leur gestion.\"" }, alternavida: { role: "Direction générale", text: "\"Alternavida se distingue par son engagement dans chaque envoi.\"" }, sandoz: { role: "Département médical", text: "\"Grâce à SELOASA, notre produit arrive en parfait état.\"" }, bbraun: { role: "Supply Chain", text: "\"Avec SELOASA, notre chaîne du froid ne faillit jamais.\"" }, arcar: { role: "Direction des opérations", text: "\"ARCAR fait pleinement confiance à la trajectoire de SELOASA.\"" }, vitalmex: { role: "Coordination logistique", text: "\"VITALMEX apprécie la ponctualité et le soin extrême apportés à chaque envoi.\"" } } }
    }
  }
};
